### ISSUE TITLE
What affinity propagation implementation do you use?

### ISSUE THREAD

**Issue by pdiffley** [mlampros/SuperpixelImageSegmentation#2]
Could you provide a link to a doc page for the AP implementation you use in this package? I tried comparing ClusterR's AP function to the AP function called in "superPx_AP_Kmeans_Segment.cpp", but the argument lists do not match up.

**Comment by mlampros** [comment]
Hi @pdiffley,

the 'SuperpixelImageSegmentation' package uses the ClusterR Rcpp header files directly. That means it calls both the [ClusterRHeader.h](https://github.com/mlampros/SuperpixelImageSegmentation/blob/master/src/superPx_AP_Kmeans_Segment.cpp#L2) and the [affinity_propagation.h](https://github.com/mlampros/SuperpixelImageSegmentation/blob/master/src/superPx_AP_Kmeans_Segment.cpp#L3) Rcpp header files of the ClusterR package. I explained it in the [README.md](https://github.com/mlampros/ClusterR/blob/master/README.md) file of the ClusterR package how this can be done in detail when someone intends to utilize the Rcpp code of one R package to another R package.
I didn't modify the AP algorithm of the ClusterR package. The AP algorithm is a [re-implementation](https://github.com/mlampros/ClusterR/blob/master/inst/include/affinity_propagation.h#L2-L12) of the Matlab code in Rcpp. 
Hopefully, I understand your question correctly.

**Comment by pdiffley** [comment]
That answers my question. Thank you!
