### ISSUE TITLE
Forcing n clusters

### ISSUE THREAD

**Issue by kueckelj** [mlampros/SuperpixelImageSegmentation#4]
Hello mlampros, 
thanks for the implementation of SLICAP in R. I am wondering if it is possible to force the number of clusters/masks. 

An example: 
I am using `$spixel_segmentation()` with `adjust_centroids_and_return_masks = TRUE` on images with human histological tissue [like this one here](https://d13ecnd8k9ud7e.cloudfront.net/wp-content/uploads/2021/08/Human-spinal-cord-cross-section-histology-slides-7-%C2%B5m-sec.-HE-Stain-human-histology-slides-wholesale-supplier.jpg). The example below shows the code I am using. 

```
library(SuperpixelImageSegmentation)
library(EBImage)
  
img <-readImage("https://d13ecnd8k9ud7e.cloudfront.net/wp-content/uploads/2021/08/Human-spinal-cord-cross-section-histology-slides-7-%C2%B5m-sec.-HE-Stain-human-histology-slides-wholesale-supplier.jpg")

init <- SuperpixelImageSegmentation::Image_Segmentation$new()

spx_masks = init$spixel_segmentation(input_image = img,
                                     method = "slic",
                                     compactness_factor = 20,
                                     superpixel = 600,
                                     AP_data = TRUE,
                                     use_median = TRUE,
                                     sim_wL = 3,
                                     sim_wA = 10,
                                     sim_wB = 10,
                                     sim_color_radius = 10,
                                     kmeans_method = "kmeans",
                                     kmeans_initializer = "kmeans++",
                                     adjust_centroids_and_return_masks = TRUE,
                                     verbose = TRUE)

init$spixel_masks_show(display_all = TRUE)

```
As the background is homogenous it is recognized as one cluster. But the tissue itself is divided in two further clusters. I am only interested in "which pixels are background and which are not", thus two clusters would suffice. These noisy pixels around the tissue are not a problem. Is there a way to force two clusters? 

Thanks in advance. 

Best regards 

Jan  
`

**Comment by mlampros** [comment]
hi @kueckelj and I'm sorry for not replying earlier. Would my previous answer to a [similar issue](https://github.com/mlampros/SuperpixelImageSegmentation/issues/3#issuecomment-1353535087) answer your question? I mention in the code snippet how you can separate the background from the remaining classes.

**Comment by mlampros** [comment]
I'll close the issue for now. Feel free to re-open it in case the code does not work as expected.
